import type {Locale} from '@/i18n/routing';

// Localized labels for transport-booking field keys. The backend sends English
// labels; this maps each field key to a localized label per UI locale. Unknown
// keys fall back to the provided (English) label.

const EN: Record<string, string> = {
  edireference: 'EDI reference',
  reference: 'Reference',
  customer_id: 'Customer ID',
  shipment_edireference: 'Shipment EDI reference',
  shipment_reference: 'Shipment reference',
  pickup_reference: 'Pickup reference',
  pickup_date: 'Pickup date',
  pickup_time: 'Pickup time',
  pickup_time_till: 'Pickup time till',
  pickup_time_delivery: 'Pickup time delivery',
  pickup_name: 'Pickup name',
  pickup_address: 'Pickup address',
  pickup_address2: 'Pickup address 2',
  pickup_country: 'Pickup country',
  pickup_zipcode: 'Pickup zipcode',
  pickup_city: 'Pickup city',
  pickup_remarks: 'Pickup remarks',
  pickup_contact: 'Pickup contact',
  pickup_phone: 'Pickup phone',
  pickup_email: 'Pickup email',
  neutral_pickup_address: 'Neutral pickup address',
  driver_pickup_info: 'Driver pickup info',
  delivery_reference: 'Delivery reference',
  delivery_date: 'Delivery date',
  delivery_time: 'Delivery time',
  delivery_time_till: 'Delivery time till',
  delivery_time_delivery: 'Delivery time delivery',
  delivery_name: 'Delivery name',
  delivery_address: 'Delivery address',
  delivery_address2: 'Delivery address 2',
  delivery_country: 'Delivery country',
  delivery_zipcode: 'Delivery zipcode',
  delivery_city: 'Delivery city',
  delivery_remarks: 'Delivery remarks',
  delivery_contact: 'Delivery contact',
  delivery_phone: 'Delivery phone',
  delivery_email: 'Delivery email',
  neutral_delivery_address: 'Neutral delivery address',
  driver_delivery_info: 'Driver delivery info',
  unit_amount: 'Unit amount',
  unit_id: 'Unit id',
  weight: 'Weight',
  cargo_unit_amount: 'Cargo unit amount',
  cargo_unit_id: 'Cargo unit id',
  cargo_weight: 'Cargo weight',
  invoice_reference: 'Invoice reference',
  product_id: 'Product',
  product_description: 'Product description',
  cargo_loading_meter: 'Cargo loading meter',
  cargo_volume: 'Cargo volume',
  pallet_places: 'Pallet places',
  length: 'Length',
  width: 'Width',
  height: 'Height',
  transport_type: 'Transport type',
  adr_class: 'ADR class',
  dangerous_goods: 'Dangerous goods',
  fixed_price: 'Fixed price',
  external_shipment_id: 'External shipment id',
  barcode: 'Barcode',
  cmr_number: 'CMR number',
  goods_unit_amount: 'Goods unit amount',
  goods_unit_id: 'Goods unit id',
  goods_weight: 'Goods weight',
  goods_loading_meter: 'Goods loading meter',
  goods_volume: 'Goods volume',
  product_instructions: 'Product instructions',
  adr: 'ADR',
  neutral_loading: 'Neutral loading',
  neutral_unloading: 'Neutral unloading',
  sender: 'Sender',
  crane_height: 'Crane height',
  permits: 'Permits',
  escort_required: 'Escort required',
  price: 'Price'
};

const NL: Record<string, string> = {
  edireference: 'EDI-referentie',
  reference: 'Referentie',
  customer_id: 'Klantnummer',
  shipment_edireference: 'Zending EDI-referentie',
  shipment_reference: 'Zendingreferentie',
  pickup_reference: 'Laadreferentie',
  pickup_date: 'Laaddatum',
  pickup_time: 'Laadtijd',
  pickup_time_till: 'Laadtijd tot',
  pickup_time_delivery: 'Laadtijd levering',
  pickup_name: 'Laadnaam',
  pickup_address: 'Laadadres',
  pickup_address2: 'Laadadres 2',
  pickup_country: 'Laadland',
  pickup_zipcode: 'Laadpostcode',
  pickup_city: 'Laadplaats',
  pickup_remarks: 'Laadopmerkingen',
  pickup_contact: 'Laadcontact',
  pickup_phone: 'Laadtelefoon',
  pickup_email: 'Laad-e-mail',
  neutral_pickup_address: 'Neutraal laadadres',
  driver_pickup_info: 'Chauffeur laadinfo',
  delivery_reference: 'Losreferentie',
  delivery_date: 'Losdatum',
  delivery_time: 'Lostijd',
  delivery_time_till: 'Lostijd tot',
  delivery_time_delivery: 'Lostijd levering',
  delivery_name: 'Losnaam',
  delivery_address: 'Losadres',
  delivery_address2: 'Losadres 2',
  delivery_country: 'Losland',
  delivery_zipcode: 'Lospostcode',
  delivery_city: 'Losplaats',
  delivery_remarks: 'Losopmerkingen',
  delivery_contact: 'Loscontact',
  delivery_phone: 'Lostelefoon',
  delivery_email: 'Los-e-mail',
  neutral_delivery_address: 'Neutraal losadres',
  driver_delivery_info: 'Chauffeur losinfo',
  unit_amount: 'Aantal eenheden',
  unit_id: 'Eenheid',
  weight: 'Gewicht',
  cargo_unit_amount: 'Aantal colli',
  cargo_unit_id: 'Eenheid lading',
  cargo_weight: 'Ladinggewicht',
  invoice_reference: 'Factuurreferentie',
  product_id: 'Product',
  product_description: 'Productomschrijving',
  cargo_loading_meter: 'Laadmeter',
  cargo_volume: 'Volume',
  pallet_places: 'Palletplaatsen',
  length: 'Lengte',
  width: 'Breedte',
  height: 'Hoogte',
  transport_type: 'Transportsoort',
  adr_class: 'ADR-klasse',
  dangerous_goods: 'Gevaarlijke goederen',
  fixed_price: 'Vaste prijs',
  external_shipment_id: 'Externe zending-id',
  barcode: 'Barcode',
  cmr_number: 'CMR-nummer',
  goods_unit_amount: 'Aantal goederen',
  goods_unit_id: 'Goederen-eenheid',
  goods_weight: 'Goederengewicht',
  goods_loading_meter: 'Goederen laadmeter',
  goods_volume: 'Goederenvolume',
  product_instructions: 'Productinstructies',
  adr: 'ADR',
  neutral_loading: 'Neutraal laden',
  neutral_unloading: 'Neutraal lossen',
  sender: 'Afzender',
  crane_height: 'Kraanhoogte',
  permits: 'Vergunningen',
  escort_required: 'Begeleiding vereist',
  price: 'Prijs'
};

const PT: Record<string, string> = {
  edireference: 'Referência EDI',
  reference: 'Referência',
  customer_id: 'ID do cliente',
  shipment_edireference: 'Referência EDI da remessa',
  shipment_reference: 'Referência da remessa',
  pickup_reference: 'Referência de coleta',
  pickup_date: 'Data de coleta',
  pickup_time: 'Hora de coleta',
  pickup_time_till: 'Hora de coleta até',
  pickup_time_delivery: 'Hora de coleta (entrega)',
  pickup_name: 'Nome de coleta',
  pickup_address: 'Endereço de coleta',
  pickup_address2: 'Endereço de coleta 2',
  pickup_country: 'País de coleta',
  pickup_zipcode: 'CEP de coleta',
  pickup_city: 'Cidade de coleta',
  pickup_remarks: 'Observações de coleta',
  pickup_contact: 'Contato de coleta',
  pickup_phone: 'Telefone de coleta',
  pickup_email: 'E-mail de coleta',
  neutral_pickup_address: 'Endereço de coleta neutro',
  driver_pickup_info: 'Info do motorista (coleta)',
  delivery_reference: 'Referência de entrega',
  delivery_date: 'Data de entrega',
  delivery_time: 'Hora de entrega',
  delivery_time_till: 'Hora de entrega até',
  delivery_time_delivery: 'Hora de entrega (entrega)',
  delivery_name: 'Nome de entrega',
  delivery_address: 'Endereço de entrega',
  delivery_address2: 'Endereço de entrega 2',
  delivery_country: 'País de entrega',
  delivery_zipcode: 'CEP de entrega',
  delivery_city: 'Cidade de entrega',
  delivery_remarks: 'Observações de entrega',
  delivery_contact: 'Contato de entrega',
  delivery_phone: 'Telefone de entrega',
  delivery_email: 'E-mail de entrega',
  neutral_delivery_address: 'Endereço de entrega neutro',
  driver_delivery_info: 'Info do motorista (entrega)',
  unit_amount: 'Quantidade de unidades',
  unit_id: 'Unidade',
  weight: 'Peso',
  cargo_unit_amount: 'Quantidade de volumes',
  cargo_unit_id: 'Unidade da carga',
  cargo_weight: 'Peso da carga',
  invoice_reference: 'Referência da fatura',
  product_id: 'Produto',
  product_description: 'Descrição do produto',
  cargo_loading_meter: 'Metro de carga',
  cargo_volume: 'Volume',
  pallet_places: 'Lugares de palete',
  length: 'Comprimento',
  width: 'Largura',
  height: 'Altura',
  transport_type: 'Tipo de transporte',
  adr_class: 'Classe ADR',
  dangerous_goods: 'Mercadorias perigosas',
  fixed_price: 'Preço fixo',
  external_shipment_id: 'ID externo da remessa',
  barcode: 'Código de barras',
  cmr_number: 'Número CMR',
  goods_unit_amount: 'Quantidade de mercadorias',
  goods_unit_id: 'Unidade de mercadorias',
  goods_weight: 'Peso das mercadorias',
  goods_loading_meter: 'Metro de carga das mercadorias',
  goods_volume: 'Volume das mercadorias',
  product_instructions: 'Instruções do produto',
  adr: 'ADR',
  neutral_loading: 'Carregamento neutro',
  neutral_unloading: 'Descarga neutra',
  sender: 'Remetente',
  crane_height: 'Altura do guindaste',
  permits: 'Licenças',
  escort_required: 'Escolta necessária',
  price: 'Preço'
};

const FIELD_LABELS: Record<Locale, Record<string, string>> = {en: EN, nl: NL, pt: PT};

export function fieldLabel(key: string, locale: Locale, fallback?: string): string {
  return FIELD_LABELS[locale]?.[key] ?? FIELD_LABELS.en[key] ?? fallback ?? key;
}
